# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
