# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('precio', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
