# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_merge_20170626_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada2',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
